//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLibraryProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library_Description
    {
        public string ID { get; set; }
        public string Type { get; set; }
        public string Category { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Version { get; set; }
        public string Autor { get; set; }
        public string Descr { get; set; }
    }
}
